#!/usr/bin/env python

import sys
import rospy
from face_recognition_ros_wrapper.srv import *

def recognize_faces_client(image_path, new_name):
    rospy.wait_for_service('register_new_face')
    print("Found server service")
    try:
        register_new_face = rospy.ServiceProxy('register_new_face', RegisterNewFace)
        resp1 = register_new_face(image_path, new_name)
        return resp1.success_status
    except rospy.ServiceException as e:
        print("Service call failed: " + str(e))

def usage():
    return sys.argv[0] + "[image_path] [person_name]"

if __name__ == "__main__":
    if len(sys.argv) == 3:
        image_path = str(sys.argv[1])
        new_name = str(sys.argv[2])
    else:
        print(usage())
        sys.exit(1)
    print("Requesting for image path " + image_path + "\nand name: " + new_name)
    print("Response: " + str(recognize_faces_client(image_path, new_name)))
