#!/usr/bin/env python

import sys
import rospy
from face_recognition_ros_wrapper.srv import *

def recognize_faces_client(image_path):
    rospy.wait_for_service('recognize_faces')
    try:
        recognize_faces = rospy.ServiceProxy('recognize_faces', RecognizeFaces)
        resp1 = recognize_faces(image_path)
        return resp1.recognized_person
    except rospy.ServiceException as e:
        print("Service call failed: " + str(e))

def usage():
    return sys.argv[0] + "[image_path]"

if __name__ == "__main__":
    if len(sys.argv) == 2:
        image_path = str(sys.argv[1])
    else:
        print(usage())
        sys.exit(1)
    print("Requesting for image path " + image_path)
    print("Response: " + str(recognize_faces_client(image_path)))
